#! /usr/bin/bash
reboot=0

while true; do
	read -p "Do you wish to ushutdown? [Yy/Nn/Rr(reboot) default Yy] " yn
	if [ -z $yn ]; then
		yn="y"
	fi
	case $yn in
		[Yy]* ) break;;
		[Nn]* ) exit;;
		[Rr]* ) reboot=1; break;;
		* ) echo "Incorrect anser"
	esac
done

if [ $reboot -eq 1 ]; then
	reboot
else
	poweroff
fi
