#! /usr/bin/bash

declare -A dotfiles=(
["Xmonad"]="$HOME/.xmonad/xmonad.hs"
["Xmobar"]="$HOME/.xmonad/xmobarrc"
["Vim"]="$HOME/.vimrc"
["VimPlugins"]="$HOME/.vim/plugin/"
["Qtile"]="$HOME/.config/qtile/config.py"
["Alacritty"]="$HOME/.config/alacritty/alacritty.yml"
["Startx"]="$HOME/.xinitrc"
["Bash"]="$HOME/.bashrc"
["DmenuScripts"]="$HOME/dmenu-scripts"
["Quit"]=""
)

script=""
for var in "$@";
do
	if [[ "$var" == $1 ]]; then
		continue;
	elif [[ "$var" != $2 ]]; then
		script+=" "
	fi
	script+="$var"
done

choice=$(printf "%s\n" "${!dotfiles[@]}" | sort | dmenu $script -p "Dotfile: ")

if [[ "${#choice}" -eq 0 ]]; then
	exit 0
elif [ "${choice}" == "Quit" ]; then
	exit 0
fi

${1} "${dotfiles[${choice}]}"
