#! /usr/bin/bash

declare -A options=(
["LockScreen"]="slock"
["Logout"]="pkill x"
["Reboot"]="sudo systemctl reboot"
["Shutdown"]="sudo systemctl poweroff"
["Suspend"]="slock sudo systemctl suspend"
["Quit"]=""
)

script=""
for var in "$@";
do
	if [[ "$var" != $1 ]]; then
		script+=" "
	fi
	script+="$var"
done

echo $script

choice=$(printf "%s\n" ${!options[@]} | sort | dmenu ${script} -p "Shutdown: " )
if [[ "${#choice}" -eq 0 ]]; then
	exit 0
elif [[ "${choice}" == "Quit" ]]; then
	exit 0
fi

if [[ "${choice}" == "LockScreen" ]]; then
	${options["${choice}"]}
	exit 0
fi

confirm=$(printf "No\nYes" | dmenu $script -p "${choice}?: ")

if [[ "${confirm}" == "Yes" ]]; then
	${options["${choice}"]}
else
	exit 0
fi
