#! /usr/bin/env bash

monitors=$(xrandr | grep -e " connected ")

script=""
for var in "$@";
do
	if [[ "$var" != $1 ]]; then
		script+=" "
	fi
	script+="$var"
done

if [[ $(echo "$monitors" | wc -l) -eq 1 ]]; then
	xrandr --output eDP1 --mode auto --primary
	xrandr --output HDMI1 --off
	exit 0
fi

options=(
"default"
"monitor"
"duplicate"
"extend"
"external"
"quit"
)

declare -A positions=(
["above"]="--above"
["below"]="--below"
["left"]="--left-of"
["right"]="--right-of"
)

choice=""
if [[ "${#choice}" -eq 0 ]]; then
	choice=$(printf "%s\n" "${options[@]}" | dmenu $script -p "Mode: ")
fi

if [[ "${#choice}" -eq 0  ]]; then
	exit 0
elif ["${choice}" == "quit"]; then # quit
	exit 0
elif ["${choice}" == "default"]; then
	xrandr --output HDMI1 --auto --primary
	xrandr --output eDPI1 --auto --secondary --left-of HDMI1
elif [ "${choice}" == "monitor" ]; then
	xrandr --output eDP1 --auto --primary
	xrandr --output HDMI1 --off
elif [ "${choice}" == "duplicate" ]; then
	xrandr --output eDP1 --auto --primary
	xrandr --output HDMI1 --auto --same-as eDP1
elif [ "${choice}" == "extend" ]; then

	choice2=""
	if [[ "${#choice2}" -eq 0 ]]; then
		choice2=$(echo "$monitors" | awk '{ print $1 }' | dmenu $script -p "Primary: ")
	fi

	choice3=""
	if [[ "${#choice3}" -eq 0 ]]; then
		choice3=$(printf "%s\n" "${!positions[@]}" | dmenu $script -p "Sec. position: ")
	fi

	xrandr --output "$choice2" --auto --primary
	xrandr --output $(echo "$monitors" | grep -v "$choice2" | awk '{ print $1 }') --auto "${positions[$choice3]}" "$choice2"

elif [ "${choice}" == "external" ]; then
	xrandr --output HDMI1 --auto --primary
	xrandr --output eDP1 --off
fi
