#! /usr/bin/bash

script=""
for var in "$@";
do
	if [[ "$var" != $1 ]]; then
		script+=" "
	fi
	script+="$var"
done

choice=$(wmctrl -l | awk '{sum += 1}; {printf "[" sum "] "}; {for(i=4;i<=NF; i++) printf $i" "; print ""}; END {print "[0] Quit"}' | dmenu $script -l 10 -p "Choose window: ")

if [ "${choice}" == "[0] Quit" ]; then 
	exit 0
elif [[ "${#choice}" -eq 0 ]]; then
	exit 0
fi

wmctrl -a $(wmctrl -l | grep -F $(echo $choice | awk '{print $2}') | awk '{print $4}')
